services:
  - type: web
    name: blockmint
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blockmint-db
          property: connectionString
      - key: SESSION_SECRET
        value: "blockmint_prod_secret_2026"
      - key: EMAIL_USER
        value: "trackitnoww@gmail.com"
      - key: EMAIL_PASS
        value: "dxjp wcrk jhvu xufo"

databases:
  - name: blockmint-db
    plan: free
